// Generated by BUCKLESCRIPT VERSION 5.0.1-beta.1, PLEASE EDIT WITH CARE
'use strict';


var Easing = /* module */[
  /* easeIn */"easeIn",
  /* easeInEaseOut */"easeInEaseOut",
  /* easeOut */"easeOut",
  /* linear */"linear",
  /* keyboard */"keyboard"
];

exports.Easing = Easing;
/* No side effect */
