// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var Source = /* module */[];

var DefaultSource = /* module */[];

exports.Source = Source;
exports.DefaultSource = DefaultSource;
/* No side effect */
