// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReactNative = require("react-native");
var PromiseUtils$CcaBsReactNative = require("./PromiseUtils.js");

function getInitialURL(param) {
  return ReactNative.Linking.getInitialURL().then(PromiseUtils$CcaBsReactNative.nullableToOption);
}

exports.getInitialURL = getInitialURL;
/* react-native Not a pure module */
