// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -66829956,
    "disabled"
  ],
  /* tuple */[
    829237851,
    "selected"
  ]
];

function accessibilityStateToJs(param) {
  return Js_mapperRt.binarySearch(2, param, jsMapperConstantArray);
}

function accessibilityStateFromJs(param) {
  return Js_mapperRt.revSearch(2, jsMapperConstantArray, param);
}

function accessibilityStates(states) {
  return Belt_Array.map(states, accessibilityStateToJs);
}

exports.accessibilityStateToJs = accessibilityStateToJs;
exports.accessibilityStateFromJs = accessibilityStateFromJs;
exports.accessibilityStates = accessibilityStates;
/* No side effect */
