// Generated by BUCKLESCRIPT VERSION 5.0.1-beta.1, PLEASE EDIT WITH CARE
'use strict';


var small = "small";

var large = "large";

exports.small = small;
exports.large = large;
/* No side effect */
