// Generated by BUCKLESCRIPT VERSION 5.0.1-beta.1, PLEASE EDIT WITH CARE
'use strict';


var Source = /* module */[];

var DefaultSource = /* module */[];

exports.Source = Source;
exports.DefaultSource = DefaultSource;
/* No side effect */
