// Generated by BUCKLESCRIPT VERSION 5.0.1-beta.1, PLEASE EDIT WITH CARE
'use strict';


var Orientation = /* module */[
  /* landscape */"landscape",
  /* landscapeLeft */"landscape-left",
  /* landscapeRight */"landscape-right",
  /* portrait */"portrait",
  /* portraitUpsideDown */"portrait-upside-down"
];

exports.Orientation = Orientation;
/* No side effect */
